### PR TITLE
Setup splash functionality.

### PR DESCRIPTION
**Pull request by archibishop**
#### Description.
Adds splash screen functionality.

#### Screenshots 

record

### CODE REVIEW

**Comment by cmplx-xyttmt** [comment]
Hi, @archibishop. Kindly add screenshots.

**Comment by archibishop** [comment]
@cmplx-xyttmt I have added a gif image for the screenshots section.

**Review by cmplx-xyttmt — APPROVED** [review]
LGTM

**Comment by huxaiphaer** [comment]
Am concerned about the lag grey color which first comes before the splash screen, I think it's better when the user clicks the app to immediately launch the splash screen , and the best way to do this is by not using XML layouts. just use a theme (with a splash screen image set on it), it will get rid of ti..

**Review by huxaiphaer — APPROVED** [review]
LGTM

**Pull request merged**
